=encoding utf8

Доброго всем

=head1 DBIx::POS::Template

¡ ¡ ¡ ALL GLORY TO GLORIA ! ! !

=head1 NAME

DBIx::POS::Template - is a fork of L<DBIx::POS>. Define a dictionary of SQL statements in a POD dialect (POS) plus expand template sql with embedded Perl by L<Text::Template>.

=head1 SYNOPSIS

  use DBIx::POS::Template;

  my $pos = DBIx::POS::Template->new(__FILE__,);
  # or singleton DBIx::POS::Template->instance($file, ...);
  
  my $sql = $pos->{test1}->template(where => "bar = ?");
  # or
  $sql = $pos->template('test1', where => "bar = ?");
  
  =pod

  =name test1

  =desc test the DBIx::POS::Template module

  =param

    # Some arbitrary parameters as perl code (eval)
    {
        cache=>1,
    }

  =sql

    select * from foo
    where {% $where %}
    ;

  =cut

=head1 SEE ALSO

L<Pod::Parser>

L<DBIx::POS>

L<Text::Template>

=head1 AUTHOR

Михаил Че (Mikhail Che), C<< <mche[-at-]cpan.org> >>

=head1 COPYRIGHT

Copyright 2016 Mikhail Che.

This module is free software; you can redistribute it and/or modify it under the term of the Perl itself.

=cut